---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: spark-webhook
webhooks:
- name: spark-webhook.kube-system.svc
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  clientConfig:
    url: https://spark-webhook.kube-system.svc.sz.k8stest.com/mutating-pods
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1ETXlOekUwTURrd00xb1hEVEk0TURNeU5ERTBNRGt3TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVZwCkMxVkdOTXc2eUo0U2UveDg1cHhFdEZSL21IZmRVL3RySTB6ZG1EWUhQb3VCbTJNK2E4VWEybGtQVy9kMjhVdGQKWGhSK1oyWUduSTlZQXhSdjVLOGMrKy8vVmRpRFl3Y2tNQ0UzWWVWajFWQjVGS21mV28vMjBocVF5MkdYMm9oLwptWWRTN3liTEVhY2xSc2Q0eFNSOEpJK3dId0JxN2JYVzBjdEhPZFJqQ2VaU1U3dFZnNGlWQnlyWTg3VEhJQ2FiClRDTVJOdmk1U2orRWxLWWk5NCt1N1JYM055NzBoVDhmbVJZcHNjZ3JZTkQ4bHVmTXIzcFlVUU80YkZ4QWVtUkoKV1l5NmV4aTAyMVR6ZGQ2bGxJdk1Oa1kwMktlNkRYWDZPMXNTUEdidHV3bGJicGtTc3BnVCtFL2d6TUZPYmFxdwpaMzQwamJnRFpGbk5jTG1SSTlNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGa243OTVvelVwTkUweVdmeWpzMnFHRWJJS2UKczNsdUw0bmJlSjhqTDVMRFVONjB5aExJTDRZRUowTjVHY0cxSlV0S21zMkRXSkRJVHZWUjNWNnQ2a2lBVU5jSApPVW9JdTNOV3ZIZW8rNWtkcG9DdmhtSVE3c3liZW9sNXRxNkRGWUVWUUVkMTRXdzlWamR3VnVEYVdQVGdKemd0CldNbklvaURxMnN2R3JWNnpsQXZVTkFRZk9Gb0FITmhIVEVIcEx4N0Q0VFBUb2lYSWoxRWJRcGlHeFVUd3ZRN1kKWTg3a2FKMG1MQ2JhRDA1c2x6dm9UbCtUNnJpZTlUaFhHakE5WE9oRzZWSzRTQXJTaDdYSE82RXhhQ3l4NDlvRwpmRGc3d29JQ3FpNVJ1VlZsUmw4Mml2dlVZdzlXWWVsUi9BK3dEKytFaHhpeklwMEFnYWlJd1pWR0ZqST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
