---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ipallocator-server-config
  namespace: kube-system
data:
  config.conf: |-
    {
      "port": 9000,
      "range_cidr": "172.18.16.0/21",
      "subnet": "172.18.0.0/17",
      "base_key": "/ipallocator/podips",
      "registry_key": "/ipallocator/ipregistry",
      "etcd_ips": [
        "http://172.18.2.3:2379"
      ],
      "routes": [
        {
          "dst": "0.0.0.0/0",
          "gw": "172.18.127.254"
        }
      ]
    }
